/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"

enum state { menu, notif };
enum state s;
typedef struct _uib_view1_control_context {
 /* add your variables here */



} uib_view1_control_context;

void view1_button1_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	if(s == menu){
		elm_object_text_set(vc->label2,"Random notif");
		elm_object_text_set(vc->button2,"Skip");
		s = notif;

	}else {
		elm_object_text_set(vc->label2,"My Foxtrotters Watch");
		elm_object_text_set(vc->button2,"");
		s = menu;
	}

}

void view1_onuib_view_create(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	s = menu;
}

